-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 09:15:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phpdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phpdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phpdb` DEFAULT CHARACTER SET utf8 ;
USE `phpdb` ;

-- -----------------------------------------------------
-- Table `phpdb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpdb`.`perfil` (
  `id` INT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phpdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpdb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(6) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  `perfil_id` INT NOT NULL,
  INDEX `fk_usuario_perfil_idx` (`perfil_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `phpdb`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phpdb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpdb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nomeC` VARCHAR(90) NOT NULL,
  `emailC` VARCHAR(90) NOT NULL,
  `telefoneC` VARCHAR(11) NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_perfil1_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_cliente_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `phpdb`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
